ubuntu@ip-172-31-23-178:~/spark-2.2.0-bin-hadoop2.7/bin$ ./spark-submit --master spark://172.31.23.178:6066  --deploy-mode client  --class spark.process.SparkMainForEachWriter /home/ubuntu/spark-2.2.0-bin-hadoop2.7/jars/sparkstreaming-0.0.1-selfcontained.jar
java.lang.NoClassDefFoundError: com/twitter/bijection/Injection
	at com.twitter.bijection.avro.GenericAvroCodecs.toBinary(AvroCodecs.scala)
	at spark.process.SparkMainForEachWriter.<clinit>(SparkMainForEachWriter.java:66)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:225)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:686)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.twitter.bijection.Injection
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more